#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Window_Form_App
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sinh_vien")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlop_hoc(lop_hoc instance);
    partial void Updatelop_hoc(lop_hoc instance);
    partial void Deletelop_hoc(lop_hoc instance);
    partial void Insertsinh_vien(sinh_vien instance);
    partial void Updatesinh_vien(sinh_vien instance);
    partial void Deletesinh_vien(sinh_vien instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Window_Form_App.Properties.Settings.Default.sinh_vienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<lop_hoc> lop_hocs
		{
			get
			{
				return this.GetTable<lop_hoc>();
			}
		}
		
		public System.Data.Linq.Table<sinh_vien> sinh_viens
		{
			get
			{
				return this.GetTable<sinh_vien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lop_hoc")]
	public partial class lop_hoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_id;
		
		private string _ma_lop;
		
		private string _ten_lop;
		
		private string _ghi_chu;
		
		private EntitySet<sinh_vien> _sinh_viens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_idChanging(int value);
    partial void Onma_idChanged();
    partial void Onma_lopChanging(string value);
    partial void Onma_lopChanged();
    partial void Onten_lopChanging(string value);
    partial void Onten_lopChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public lop_hoc()
		{
			this._sinh_viens = new EntitySet<sinh_vien>(new Action<sinh_vien>(this.attach_sinh_viens), new Action<sinh_vien>(this.detach_sinh_viens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_id
		{
			get
			{
				return this._ma_id;
			}
			set
			{
				if ((this._ma_id != value))
				{
					this.Onma_idChanging(value);
					this.SendPropertyChanging();
					this._ma_id = value;
					this.SendPropertyChanged("ma_id");
					this.Onma_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_lop", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ma_lop
		{
			get
			{
				return this._ma_lop;
			}
			set
			{
				if ((this._ma_lop != value))
				{
					this.Onma_lopChanging(value);
					this.SendPropertyChanging();
					this._ma_lop = value;
					this.SendPropertyChanged("ma_lop");
					this.Onma_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_lop", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_lop
		{
			get
			{
				return this._ten_lop;
			}
			set
			{
				if ((this._ten_lop != value))
				{
					this.Onten_lopChanging(value);
					this.SendPropertyChanging();
					this._ten_lop = value;
					this.SendPropertyChanged("ten_lop");
					this.Onten_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(255)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lop_hoc_sinh_vien", Storage="_sinh_viens", ThisKey="ma_lop", OtherKey="ma_lop")]
		public EntitySet<sinh_vien> sinh_viens
		{
			get
			{
				return this._sinh_viens;
			}
			set
			{
				this._sinh_viens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sinh_viens(sinh_vien entity)
		{
			this.SendPropertyChanging();
			entity.lop_hoc = this;
		}
		
		private void detach_sinh_viens(sinh_vien entity)
		{
			this.SendPropertyChanging();
			entity.lop_hoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinh_vien")]
	public partial class sinh_vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_sv;
		
		private string _ho_ten;
		
		private System.DateTime _ngay_sinh;
		
		private string _gioi_tinh;
		
		private string _ma_lop;
		
		private EntityRef<lop_hoc> _lop_hoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_svChanging(string value);
    partial void Onma_svChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onngay_sinhChanging(System.DateTime value);
    partial void Onngay_sinhChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void Onma_lopChanging(string value);
    partial void Onma_lopChanged();
    #endregion
		
		public sinh_vien()
		{
			this._lop_hoc = default(EntityRef<lop_hoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sv", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_sv
		{
			get
			{
				return this._ma_sv;
			}
			set
			{
				if ((this._ma_sv != value))
				{
					this.Onma_svChanging(value);
					this.SendPropertyChanging();
					this._ma_sv = value;
					this.SendPropertyChanged("ma_sv");
					this.Onma_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date NOT NULL")]
		public System.DateTime ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_lop", DbType="VarChar(20)")]
		public string ma_lop
		{
			get
			{
				return this._ma_lop;
			}
			set
			{
				if ((this._ma_lop != value))
				{
					if (this._lop_hoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_lopChanging(value);
					this.SendPropertyChanging();
					this._ma_lop = value;
					this.SendPropertyChanged("ma_lop");
					this.Onma_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lop_hoc_sinh_vien", Storage="_lop_hoc", ThisKey="ma_lop", OtherKey="ma_lop", IsForeignKey=true)]
		public lop_hoc lop_hoc
		{
			get
			{
				return this._lop_hoc.Entity;
			}
			set
			{
				lop_hoc previousValue = this._lop_hoc.Entity;
				if (((previousValue != value) 
							|| (this._lop_hoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lop_hoc.Entity = null;
						previousValue.sinh_viens.Remove(this);
					}
					this._lop_hoc.Entity = value;
					if ((value != null))
					{
						value.sinh_viens.Add(this);
						this._ma_lop = value.ma_lop;
					}
					else
					{
						this._ma_lop = default(string);
					}
					this.SendPropertyChanged("lop_hoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
